# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38ca30c4d44abae2714081db310b1c12f2c9f680e7b9be21f39a82740dce2c04196a0a2a8de92dca0bcc3d7be7ecfbb3747057f97afa13db737af90eb6ce7359

test:
  secret_key_base: e71b72ba5a7c0a3647f7c3ec3125e69c1446eb69649dc9f80f026836ba84bb802b8ecb696b1776ec0c31d45589c7d5471e23843faa857f80d5ba989434389ea1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
